# Generated by Django 3.2.4 on 2021-06-20 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoomit_categories', '0003_rename_url_category_slug'),
        ('zoomit_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zoomit_categories.category'),
        ),
    ]
