# Generated by Django 3.2.4 on 2021-06-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoomit_tags', '0001_initial'),
        ('zoomit_posts', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(null=True, to='zoomit_tags.Tag'),
        ),
    ]
