# Generated by Django 3.2.4 on 2021-07-02 13:12

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zoomit_posts', '0008_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=django_editorjs.fields.EditorJsField(null=True),
        ),
    ]
