# Generated by Django 3.2.4 on 2021-07-02 13:23

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zoomit_posts', '0009_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_editorjs_fields.fields.EditorJsJSONField(null=True),
        ),
    ]
