# Generated by Django 3.2.4 on 2021-06-20 10:42

from django.db import migrations, models
import zoomit_ads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('link', models.URLField(max_length=255, verbose_name='آدرس اینترنتی')),
                ('image', models.ImageField(upload_to=zoomit_ads.models.upload_path, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
            },
        ),
    ]
