# Generated by Django 3.2.4 on 2021-06-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان برچسب')),
                ('slug', models.SlugField(max_length=200, verbose_name='عنوان در آدرس')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسبها',
            },
        ),
    ]
