# Generated by Django 3.2.4 on 2021-06-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoomit_comments', '0002_usercommentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='user_image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
