# Generated by Django 3.2.4 on 2021-06-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoomit_comments', '0004_usercommentreply_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='user_image',
        ),
        migrations.RemoveField(
            model_name='usercommentreply',
            name='user_image',
        ),
    ]
