# Generated by Django 3.2.4 on 2021-06-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoomit_comments', '0005_auto_20210624_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='user_image',
            field=models.ImageField(default='ali.png', null=True, upload_to='user/update/'),
        ),
        migrations.AddField(
            model_name='usercommentreply',
            name='user_image',
            field=models.ImageField(default='ali.png', upload_to='user/update/'),
        ),
        migrations.AlterField(
            model_name='usercommentreply',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
