# Generated by Django 3.2.4 on 2021-06-24 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zoomit_comments', '0006_auto_20210624_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='user_image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usercommentreply',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercommentreply',
            name='user_image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
