# Generated by Django 3.2.4 on 2021-07-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoomit_comments', '0007_auto_20210624_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='usercommentreply',
            options={'verbose_name': 'جواب', 'verbose_name_plural': 'جواب ها'},
        ),
    ]
