# Generated by Django 3.2.4 on 2021-06-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoomit_savelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savelist',
            options={'verbose_name': 'پست', 'verbose_name_plural': 'دخیره شده ها'},
        ),
    ]
