# Generated by Django 3.2.4 on 2021-06-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoomit_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان دسته بندی'),
        ),
    ]
