# Generated by Django 3.2.4 on 2021-06-24 16:58

from django.db import migrations, models
import zoomit_media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to=zoomit_media.models.upload_path)),
            ],
        ),
    ]
